CREATE TABLE `splunk_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`hecUrl` varchar(512) NOT NULL,
	`hecToken` varchar(256) NOT NULL,
	`index` varchar(128) DEFAULT 'main',
	`source` varchar(128) DEFAULT 'second-sight-rf',
	`sourcetype` varchar(128) DEFAULT 'rf_signal_analysis',
	`enabledEventTypes` text,
	`verifySsl` boolean NOT NULL DEFAULT true,
	`batchSize` int NOT NULL DEFAULT 10,
	`flushInterval` int NOT NULL DEFAULT 5000,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTestAt` timestamp,
	`lastTestSuccess` boolean,
	`lastTestMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `splunk_config_id` PRIMARY KEY(`id`)
);
